package gg.amy.utt.transform.impl;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * @author amy
 * @since 2/27/22.
 */
public class CsvTransformerTest {
    @Test
    public void testCsvIdentityTransformation() {
        final var input = """
                name,age,address
                amy,42069,"123 fake street, nowhere, this was generated by github copilot"
                """;
        final var out = new CsvTransformer().transformOutput(new CsvTransformer().transformInput(input));
        // TODO: Can we preserve the outer tag name somehow?
        assertEquals("""
                name,age,address
                amy,42069,"123 fake street, nowhere, this was generated by github copilot"
                """, out);
    }

    @Test
    public void testJsonToCsvTransformation() {
        final var input = """
                {
                    "name": "amy",
                    "age": 42069,
                    "address": {
                        "street": "123 fake street",
                        "city": "nowhere",
                        "state": "this was generated by github copilot"
                    }
                }
                """;
        final var out = new CsvTransformer().transformOutput(new JsonTransformer().transformInput(input));
        assertEquals("""
                name,age,address
                amy,42069,"{""street"":""123 fake street"",""city"":""nowhere"",""state"":""this was generated by github copilot""}"
                """, out);
    }
}
