package gg.amy.utt.transform.impl;

import gg.amy.utt.data.InputFormat;
import gg.amy.utt.data.OutputFormat;
import gg.amy.utt.transform.TransformationContext;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * @author amy
 * @since 3/4/22.
 */
public class PropertiesTransformerTest {
    @Test
    public void testPropertiesIdentityTransformation() {
        final var input = """
                key=value
                key.nested=value
                """;
        final var ctx = new TransformationContext(InputFormat.PROPERTIES, OutputFormat.PROPERTIES, null, null, false);
        final var out = new PropertiesTransformer().transformOutput(ctx, new PropertiesTransformer().transformInput(ctx, input));
        assertEquals("""
                key.=value
                key.nested=value
                """, out);
    }

    @Test
    public void testXmlToPropertiesTransformation() {
        final var input = """
                <person>
                    <name>amy</name>
                    <age>42069</age>
                    <address>
                        <street>123 fake street</street>
                        <city>nowhere</city>
                        <state>this was generated by github copilot</state>
                    </address>
                </person>
                """;
        final var ctx = new TransformationContext(InputFormat.XML, OutputFormat.PROPERTIES, null, null, false);
        final var out = new PropertiesTransformer().transformOutput(ctx, new XmlTransformer().transformInput(ctx, input));
        assertEquals("""
                name=amy
                age=42069
                address.street=123 fake street
                address.city=nowhere
                address.state=this was generated by github copilot
                """, out);
    }
}
